language: rust
rust: beta

# https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
  before_cache:
    - rm -rf /home/travis/.cargo/registry

branches:
  only:
    - staging
    - trying
    - master

matrix:
  fast_finish: true
  allow_failures:
    - name: coverage
  include:
    - name: tests
      script:
        - cargo test --all --all-features
        - cargo doc --all --all-features --no-deps
    - name: style
      install:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cargo clippy --all --all-features --all-targets --tests -- -D warnings
        - cargo fmt --all -- --check
    - name: no-default-features
      script:
        - cargo test --all --no-default-features
    - name: coverage
      rust: nightly-2019-08-08
      sudo: required
      cache: cargo
      env: RUSTFLAGS="--cfg procmacro2_semver_exempt"
      addons:
        apt:
          packages:
            - libssl-dev
      install:
        - cargo install cargo-update || true
        - cargo install-update -i cargo-tarpaulin cargo-update
      script:
        - cargo tarpaulin --all-features --out Xml
      after_success:
        - bash <(curl -s https://codecov.io/bash)
